// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadTasks():Promise<string>;

export function SaveTasks(arg1:string):Promise<boolean>;
